# Generated by Django 3.2.12 on 2023-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_auto_20230408_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.CharField(blank=True, help_text='시스템 프롬프트', max_length=45, null=True)),
                ('prompt', models.TextField(help_text='프롬프트')),
                ('summary', models.TextField(blank=True, help_text='요약', null=True)),
                ('tag', models.CharField(blank=True, help_text='태그', max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ChatGPT 질문지',
                'verbose_name_plural': 'ChatGPT 질문지',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'ChatGPT 응답 마지막 결과', 'verbose_name_plural': 'ChatGPT 응답 마지막 결과'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='태그', max_length=45, null=True),
        ),
    ]
