# Generated by Django 3.2.12 on 2023-04-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0004_create_lesson_information_default_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoninformation',
            name='summary',
            field=models.TextField(blank=True, help_text='요약', null=True),
        ),
    ]
