# Generated by Django 3.2.12 on 2022-03-18 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0010_auto_20220318_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_message', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '알림 중재자',
                'verbose_name_plural': '알림 중재자',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '알림 타입',
                'verbose_name_plural': '알림 타입',
            },
        ),
        migrations.CreateModel(
            name='RereplyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationcontroller')),
                ('rereply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.rereply')),
            ],
            options={
                'verbose_name': '대댓글 알림',
                'verbose_name_plural': '대댓글 알림',
            },
        ),
        migrations.CreateModel(
            name='ReplyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationcontroller')),
                ('reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.reply')),
            ],
            options={
                'verbose_name': '댓글 알림',
                'verbose_name_plural': '댓글 알림',
            },
        ),
        migrations.AddField(
            model_name='notificationcontroller',
            name='notification_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationtype'),
        ),
        migrations.AddField(
            model_name='notificationcontroller',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationcontroller',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.like')),
                ('notification_controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationcontroller')),
            ],
            options={
                'verbose_name': '좋아요 알림',
                'verbose_name_plural': '좋아요 알림',
            },
        ),
    ]
