# Generated by Django 3.2.12 on 2022-03-18 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationtype_redirect_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtype',
            old_name='redirect_url',
            new_name='lookup_model',
        ),
    ]
