# Generated by Django 3.2.12 on 2022-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220318_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
