# Generated by Django 3.1.7 on 2022-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='board_group_id',
            new_name='board_group',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='board_id',
            new_name='board',
        ),
    ]
