# Generated by Django 3.1.7 on 2022-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20220306_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rereply',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rereply',
            old_name='reply_id',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='urlimportant',
            old_name='post_id',
            new_name='post',
        ),
    ]
