# Generated by Django 3.1.7 on 2022-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20220306_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelOptions(
            name='boardgroup',
            options={'verbose_name': '게시판 종류', 'verbose_name_plural': '게시판 종류'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': '게시글 좋아요', 'verbose_name_plural': '게시글 좋아요'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='rereply',
            options={'verbose_name': '답글(댓글의댓글)', 'verbose_name_plural': '답글(댓글의댓글)'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그 목록', 'verbose_name_plural': '태그 목록'},
        ),
        migrations.AlterModelOptions(
            name='urlimportant',
            options={'verbose_name': 'URL 강조', 'verbose_name_plural': 'URL 강조'},
        ),
    ]
