# Generated by Django 3.1.7 on 2022-03-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_board_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='info_background_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
