# Generated by Django 3.1.7 on 2022-03-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20220315_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name_background_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='name_text_color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
