# Generated by Django 3.1.7 on 2022-04-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20220406_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_active',
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
