# Generated by Django 3.1.7 on 2022-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_todayyesterday_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announce',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AlterModelOptions(
            name='ipvisitant',
            options={'verbose_name': '방문자 IP', 'verbose_name_plural': '방문자 IP'},
        ),
        migrations.AlterModelOptions(
            name='todayyesterday',
            options={'verbose_name': '방문자 수', 'verbose_name_plural': '방문자 수'},
        ),
    ]
