name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Master Branch
      run: |
        cd /var/www/null_blog/ && sudo git pull origin master

    - name: Collectstatic
      run: |
        . /var/www/null_blog/venv/bin/activate && python /var/www/null_blog/manage.py collectstatic --noinput

    - name: Database Update
      run: |
        . /var/www/null_blog/venv/bin/activate && python /var/www/null_blog/manage.py migrate --noinput

    - name: Restart server
      run: |
        sudo systemctl restart nginx
        sudo systemctl restart uwsgi